### ISSUE TITLE
Integración con recuento y modificación

### ISSUE THREAD

**Issue by agubelu** [AgoraUS-G1-1617/CabinaTelegram#11]
Hola, creo que sería conveniente que la cabina de votación de telegram se integrara con nosotros.

En este momento podemos almacenar y listar votaciones, así como emitir, editar y eliminar votos en las mismas. El recuento de votos estará disponible pronto.

Tenéis toda la documentación de la API en nuestra rama de desarrollo: https://github.com/AgoraUS-G1-1617/Recuento-y-modificacion/tree/development

**Comment by jossalgon** [comment]
De acuerdo, lo pongo en proceso y durante estos días realizaremos la integración, gracias por comentarlo.
