### ISSUE TITLE
Integración con Almacenamiento

### ISSUE THREAD

**Issue by FerminFB** [AgoraUS-G1-1617/CabinaTelegram#31]
El subsistema de almacenamiento ya esta en integración continua, podéis confirmarnos que os funciona nuestra API ?

**Comment by jossalgon** [comment]
Lo siento pero no podemos integrar un día antes de la entrega. Si los parámetros fueran similares a los de enviar voto en recuento se podría estudiar, pero estando así y ya integrado con recuento no nos sera posible.
